Respect Config for Search API Endpoints
ral-facilities/datagateway-api pull request #290
Opened 2021-11-16 17:44 UTC by VKTB

This PR will close #283

## Description
Enter a description of the changes here

## Testing Instructions
Add a set up instructions describing how the reviewer should test the code

- [ ] Review code
- [ ] Check GitHub Actions build
- [ ] If `icatdb Generator Script Consistency Test` CI job fails, is this because of a deliberate change made to the script to change generated data (which isn't actually a problem) or is here an underlying issue with the changes made?
- [ ] Review changes to test coverage
- [ ] Does this change mean a new patch, minor or major version should be made? If so, does one of the commit messages feature `fix:`, `feat:` or `BREAKING CHANGE:` so a release is automatically made via GitHub Actions upon merge?
- [ ] {more steps here}

## Agile Board Tracking
Connect to #283

2021-11-18 09:22 UTC, VKTB commented
Louise asked if any of the APIs can be served at `/` when a blank extension is provided in the config. With the changes at the moment this will cause issues because the API extension is injected between two slashes in the endpoint URL - `f"/{datagateway_api_extension}/sessions",`. This should not happen so I will quickly remove the slash before the extension variable in the endpoint URLs but this would mean that the extension itself has to be prefixed with a slash in the config file. This can be enforced using pydantic in PR https://github.com/ral-facilities/datagateway-api/pull/285.

2021-11-18 13:56 UTC, MRichards99 commented
@VKTB your proposed solution sounds sensible, requiring the slash prefix in the configuration shouldn't be a problem if you can get pydantic to help with this.

2021-11-22 10:50 UTC, MRichards99 requested changes
This work looks good, and I can see that one of the APIs can be served on `/` if this is configured as such. There's 2 tiny style changes I've suggested and I think your branches need merging (on this branch and `add-datagateway-and-panosc-modes-#256`) to get the CI passing but I'd be happy to approve once this is done.

2021-11-22 10:50 UTC, MRichards99 commented on datagateway_api/src/api_start_utils.py
> +        # TODO - Use config value when new config style is implemented
This TODO can be removed because you've used the config value :)

2021-11-22 10:50 UTC, MRichards99 commented on test/datagateway_api/icat/filters/test_order_filter.py
> +
Flake8 isn't complaining about this but the standard gap between import groups is a single line. Could this additional line be removed please? I'm guessing this managed to sneak its way in by accident :)

2021-11-22 18:27 UTC, MRichards99 submitted a review, later dismissed

2021-11-23 10:03 UTC, MRichards99 approved these changes
Ready to merge when you're ready

2021-11-23 10:19 UTC, VKTB commented
> Ready to merge when you're ready

@MRichards99 This can now be merged.

2021-11-23 10:46 UTC, merged