Changes to tests so they pass with icat 5
ral-facilities/datagateway-api pull request #381
Opened 2022-09-22 10:15 UTC by Reillyhewitson

This PR will close #374 

## Description
I have made changes to the tests to ensure that they expect new ICAT 5 fields in the Investigation table.

## Testing Instructions
Add a set up instructions describing how the reviewer should test the code

- [ ] Review code
- [ ] Check GitHub Actions build
- [ ] If `icatdb Generator Script Consistency Test` CI job fails, is this because of a deliberate change made to the script to change generated data (which isn't actually a problem) or is here an underlying issue with the changes made?
- [ ] Review changes to test coverage
- [ ] Does this change mean a new patch, minor or major version should be made? If so, does one of the commit messages feature `fix:`, `feat:` or `BREAKING CHANGE:` so a release is automatically made via GitHub Actions upon merge?

## Agile Board Tracking
Connect to #374

2022-10-19 09:04 UTC, MRichards99 requested changes
Looks good, the tests run on my machine and on CI. Just address the minor comments and once the ICAT Ansible ref has been changed back to master, this PR can be merged.

2022-10-24 15:02 UTC, Reillyhewitson commented on .github/workflows/ci-build.yml
> +          ref: icat5
The reference has been changed and a PR on icat-ansible has been opened

2022-10-24 15:05 UTC, Reillyhewitson commented on noxfile.py
> +        )
A comment has been added in the latest commit

2022-11-03 11:21 UTC, MRichards99 approved these changes

2022-11-03 11:32 UTC, merged