Feature/icat backend generator#369
ral-facilities/datagateway-api pull request #401
Opened 2023-02-10 13:55 UTC by Reillyhewitson

This PR will close #369 

## Description
This PR updates the generator script to use the python_icat backend, it also updates the dg-api and search-api tests so that the new data passes.

## Testing Instructions
Add a set up instructions describing how the reviewer should test the code

- [ ] Review code
- [ ] Check GitHub Actions build
- [ ] If `icatdb Generator Script Consistency Test` CI job fails, is this because of a deliberate change made to the script to change generated data (which isn't actually a problem) or is here an underlying issue with the changes made?
- [ ] Review changes to test coverage
- [ ] Does this change mean a new patch, minor or major version should be made? If so, does one of the commit messages feature `fix:`, `feat:` or `BREAKING CHANGE:` so a release is automatically made via GitHub Actions upon merge?
- [ ] {more steps here}

## Agile Board Tracking
Connect to #369

2023-02-14 09:26 UTC, MRichards99 requested changes
This looks great, a really good piece of work that I know wasn't the most interesting thing to do. I've made a couple of minor comments on the generator script but it's great that it works!

2023-02-14 09:26 UTC, MRichards99 commented on util/icat_db_generator.py
> +        #    pool.map(DatafileGenerator.generate_datafile, range(1, self.amount))
Can this commented out code be removed?

2023-02-14 09:26 UTC, MRichards99 commented on util/icat_db_generator.py
> +        #    )
Can this commented out code be removed?

2023-02-16 09:04 UTC, Reillyhewitson commented on util/icat_db_generator.py
> +    pass
It was meant to see if I could bypass the icat validation applied by python_icat. It was only being used by keywords and didn't significantly change the performance so I've removed the code.

2023-02-16 09:04 UTC, Reillyhewitson commented on util/icat_db_generator.py
> +        #    )
Yes, removed.

2023-02-16 09:04 UTC, Reillyhewitson commented on util/icat_db_generator.py
> +        #    pool.map(DatafileGenerator.generate_datafile, range(1, self.amount))
Yes, removed.

2023-02-16 09:42 UTC, MRichards99 approved these changes

2023-02-17 09:26 UTC, MRichards99 approved these changes

2023-02-17 09:27 UTC, merged