refactor: remove database backend #469
ral-facilities/datagateway-api pull request #507
Opened 2024-11-26 15:50 UTC by joshuadkitenge

This PR will close #469

## Description
Enter a description of the changes here

## Testing Instructions
Add a set up instructions describing how the reviewer should test the code

- [ ] Review code
- [ ] Check GitHub Actions build
- [ ] If `icatdb Generator Script Consistency Test` CI job fails, is this because of a deliberate change made to the script to change generated data (which isn't actually a problem) or is here an underlying issue with the changes made?
- [ ] Review changes to test coverage
- [ ] Does this change mean a new patch, minor or major version should be made? If so, does one of the commit messages feature `fix:`, `feat:` or `BREAKING CHANGE:` so a release is automatically made via GitHub Actions upon merge?
- [ ] {more steps here}

## Agile Board Tracking
Connect to #469

2025-11-17 15:32 UTC, joshdimanteto commented on .github/workflows/ci-build.yml
> +          cd /home/runner/install/icat.server/ && ./setup -vv install
check if this is still needed

2025-11-17 15:49 UTC, joshdimanteto commented on .github/workflows/ci-build.yml
> +          cd /home/runner/install/icat.server/ && ./setup -vv install
it is, as it needs an ICAT server

2026-02-09 10:06 UTC, joshdimanteto commented on test/integration/conftest.py
> +    # delete_row_by_id(SESSION, "Test")
```suggestion

yield {"Authorization": f"Bearer {session.id}"}

```

2026-02-09 10:08 UTC, joshdimanteto commented on test/integration/conftest.py
>  def flask_test_app_db():
This name should change. I have changed in #524 where i had to refactored the tests

2026-02-10 17:25 UTC, VKTB commented on .github/workflows/ci-build.yml
> +          cd /home/runner/install/icat.server/ && ./setup -vv install
Just wondering why it was working before without any of this but now it needs all the ICAT stuff?

2026-02-10 17:25 UTC, VKTB commented on datagateway_api/src/common/config.py
Once migrated to pydantic v2, I would recommend that [pydantic-settings](https://docs.pydantic.dev/latest/concepts/pydantic_settings/) is used for managing the config.

2026-02-10 17:25 UTC, VKTB commented on datagateway_api/src/common/config.py
>          return value
Shouldn't the fields in the `@validator` signature now always be mandatory? If so I don't the point of having a validator, just the definition of the fields need updating.

2026-02-11 16:42 UTC, joshdimanteto commented on datagateway_api/src/common/config.py
This work before as it was using the db backend instead of the python icat backend so it didn't need the extra setup

2026-02-11 16:43 UTC, joshdimanteto commented on datagateway_api/src/common/config.py
>          return value
I've done that in the next pr but i'll copy the change into this pr https://github.com/ral-facilities/datagateway-api/pull/521/changes#diff-22481ddb482cc5158876a842b78be896b32d69bac61530202b4a831e08a5c442

2026-02-12 10:11 UTC, joshdimanteto commented on datagateway_api/src/common/config.py
I will create a separated pr to do this ([pydantic-settings](https://docs.pydantic.dev/latest/concepts/pydantic_settings/)[pydantic-settings](https://docs.pydantic.dev/latest/concepts/pydantic_settings/)). I will do this pr after the port to fast api pr #524

2026-02-12 10:12 UTC, joshdimanteto commented on datagateway_api/src/common/config.py
#526

2026-02-12 10:43 UTC, joshdimanteto commented on .github/workflows/ci-build.yml
> +          cd /home/runner/install/icat.server/ && ./setup -vv install
This work before as it was using the db backend instead of the python icat backend so it didn't need the extra setup

2026-02-24 15:16 UTC, VKTB commented on .github/workflows/ci-build.yml
> +          cd /home/runner/install/icat.server/ && ./setup -vv install
That makes sense, thanks.

2026-02-24 15:20 UTC, VKTB approved these changes
I think the changes look fine, I tried my best. I have not tested it locally as I don't have a working stack to point it it to so I just trust that it works as expected. Might be worth asking someone else to have a look too. Approving.

2026-02-26 16:47 UTC, patrick-austin requested changes
Functionally I think it's OK (I can run the API and get results back).

There's a few whitespace changes I would make (as a result of strings being moved onto one line) and one or two possible code changes.

2026-02-26 16:47 UTC, patrick-austin commented on .github/workflows/ci-build.yml
> +          java-version: 8
Given the CI for icat.server runs on 11/21 and we're looking to run 25 in production for Diamond, we can probably increase this (not that it should really change anything).

2026-02-26 16:47 UTC, patrick-austin commented on .github/workflows/ci-build.yml
> +        if: success()
```suggestion
```

As far as I know this doesn't do anything, since the [default behaviour is to only run the step if the previous ones succeeded](https://docs.github.com/en/actions/reference/workflows-and-actions/expressions#status-check-functions) - unless I'm missing something here?

2026-02-26 16:47 UTC, patrick-austin commented on datagateway_api/src/common/config.py
>          validate_assignment = True
Is setting `validate_assignment = True` still necessary at all? `set_backend_type` is gone, and searching the repo I can't see any instances where we assign a new variable to a config field, so unless there's something subtle going on, I think this can be removed?

At the very least, can edit the comment so that it's a complete sentence and doesn't end [`when the`](https://www.reddit.com/r/whenthe/)

2026-02-26 16:47 UTC, patrick-austin commented on test/integration/datagateway_api/icat/test_query.py
> +                {"title": "like '%Test data for Python ICAT on" " DataGateway API%'"},
```suggestion
                {"title": "like '%Test data for Python ICAT on DataGateway API%'"},
```

2026-02-26 16:47 UTC, patrick-austin commented on test/integration/datagateway_api/icat/test_query.py
> +                        "title": "Test data for Python ICAT on DataGateway" " API 0",
```suggestion
                        "title": "Test data for Python ICAT on DataGateway API 0",
```

2026-02-26 16:47 UTC, patrick-austin commented on test/integration/datagateway_api/icat/test_query.py
> +                {"title": "like '%Test data for Python ICAT on" " DataGateway API%'"},
```suggestion
                {"title": "like '%Test data for Python ICAT on DataGateway API%'"},
```

2026-02-26 16:47 UTC, patrick-austin commented on test/integration/datagateway_api/icat/test_query.py
> +                        "title": "Test data for Python ICAT on DataGateway" " API 0",
```suggestion
                        "title": "Test data for Python ICAT on DataGateway API 0",
```

2026-02-26 16:47 UTC, patrick-austin commented on test/integration/datagateway_api/icat/test_query.py
> +                {"title": "like '%Test data for Python ICAT on" " DataGateway API%'"},
```suggestion
                {"title": "like '%Test data for Python ICAT on DataGateway API%'"},
```

2026-02-26 16:47 UTC, patrick-austin commented on test/integration/datagateway_api/icat/test_query.py
> +                {"title": "like '%Test data for Python ICAT on" " DataGateway API%'"},
```suggestion
                {"title": "like '%Test data for Python ICAT on DataGateway API%'"},
```

2026-02-26 16:47 UTC, patrick-austin commented on test/integration/datagateway_api/icat/test_query.py
> +                        "title": "Test data for Python ICAT on DataGateway" " API 0",
```suggestion
                        "title": "Test data for Python ICAT on DataGateway API 0",
```

2026-02-26 16:47 UTC, patrick-austin commented on test/integration/datagateway_api/icat/test_query.py
> +                {"title": "like '%Test data for Python ICAT on" " DataGateway API%'"},
```suggestion
                {"title": "like '%Test data for Python ICAT on DataGateway API%'"},
```

2026-02-26 16:47 UTC, patrick-austin commented on test/integration/datagateway_api/icat/test_query.py
> +                [{"title": "Test data for Python ICAT on DataGateway" " API 0"}],
```suggestion
                [{"title": "Test data for Python ICAT on DataGateway API 0"}],
```

2026-02-26 16:47 UTC, patrick-austin commented on test/integration/datagateway_api/icat/test_query.py
> +                {"title": "like '%Test data for Python ICAT on" " DataGateway API%'"},
```suggestion
                {"title": "like '%Test data for Python ICAT on DataGateway API%'"},
```

2026-02-26 16:47 UTC, patrick-austin commented on test/integration/datagateway_api/icat/test_query.py
> +                        "title": "Test data for Python ICAT on DataGateway" " API 0",
```suggestion
                        "title": "Test data for Python ICAT on DataGateway API 0",
```

2026-02-26 16:47 UTC, patrick-austin commented on test/integration/datagateway_api/icat/test_query.py
> +                {"title": "like '%Test data for Python ICAT on" " DataGateway API%'"},
```suggestion
                {"title": "like '%Test data for Python ICAT on DataGateway API%'"},
```

2026-02-26 16:47 UTC, patrick-austin commented on README.md
> +The tests are split into 2 main sections: non Python ICAT specific (testing features such as the date handler) and python ICAT
```suggestion
The tests are split into 2 main sections: non Python ICAT specific (testing features such as the date handler) and Python ICAT
```

2026-02-26 16:47 UTC, patrick-austin commented on README.md
> +this is used for interacting with ICAT objects within Python ICAT. In most instances, the
```suggestion
This is used for interacting with ICAT objects within Python ICAT. In most instances, the
```

2026-02-26 16:47 UTC, patrick-austin commented on README.md
> +ready for storing in ICAT. The handler is currently only used in the Python ICAT.
```suggestion
ready for storing in ICAT.
```

2026-02-26 16:47 UTC, patrick-austin commented on README.md
> +creating and updating data uses camelCase attribute names as accepted by that python_icat).
For me it doesn't really make sense to say it's mainly based around Python ICAT, at is it implies it is partially based around something else (i.e. the DB) that no longer exists at all - but I don't think it's a big deal either way.

2026-02-26 16:48 UTC, patrick-austin commented on .github/workflows/ci-build.yml
> +          java-version: 8
Alan says 11 would be best.

2026-02-26 16:50 UTC, patrick-austin commented on .github/workflows/ci-build.yml
> +          java-version: 8
He also says that actually this won't matter as icat-ansible will install java itself, so we don't need this step at all (big if true).

2026-02-26 17:09 UTC, patrick-austin commented on .github/workflows/ci-build.yml
> +          java-version: 8
He also says to use the payara7 branch

2026-02-27 09:18 UTC, joshdimanteto commented on README.md
> +creating and updating data uses camelCase attribute names as accepted by that python_icat).
I am going to removed those two line as datagateway-api only use python icat now

2026-02-27 14:11 UTC, patrick-austin approved these changes
As discussed over Teams, there are some instances where the models do not strictly represent the types/fields required by the API (for example required fields when POSTing or id when PATCHing).

However, given that further changes are in progress with the FastAPI refactor and the primary use case for the API is DataGateway's read operations, I'm happy that the use of Optional lets things work for now, and it doesn't matter so much that someone referring to the Swagger wouldn't know id is required for PATCH (as who's looking at the Swagger in the first place?)

2026-03-16 09:56 UTC, merged